version: '3'

services:

  back:
    container_name: symfony-back
    hostname: symfony-back
    build: ./data/web/back
    restart: "no"
    depends_on: 
      - mysql
    ports:
      - ${BACK_PORT}:8000
    volumes:
      - ./data/web/back:/app
    networks:
      - back_db

  react:
    container_name: react
    build: ./data/web/front
    command: npm start
    volumes:
      - ./data/web/front/:/usr/app
      - /usr/app/node_modules
    ports:
      - ${FRONT_PORT}:3000  

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - "./scripts/database.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/user.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/triggers.sql:/docker-entrypoint-initdb.d/3.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/4.sql"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - back_db
      - pma_db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=${PMA_HOST}
    networks:
      - pma_db

networks:
  api_db:
  back_db:
  pma_db: