#!/bin/bash
INSTDIR=/var/www/slim
PROJDIR=.

function die() {
        echo "Echec d'installation !!!"
        echo $1
        exit -1
}

mkdir -p $INSTDIR
test -d $INSTDIR || die "Impossible de se deplacer dans le repertoire $INSTDIR"
cd $INSTDIR
if [ -z "$(ls -A .)" ]
then
	composer create-project slim/slim-skeleton $PROJDIR
	chmod 700 $PROJDIR/logs
fi

docker-php-entrypoint "$@"
